//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareGroup.Mirrors.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisGroup
    {
        public AnalysisGroup()
        {
            this.Analyses = new HashSet<Analysis>();
        }
    
        public int AnalysisGroupID { get; set; }
        public string AnalysisGroupName { get; set; }
    
        public virtual ICollection<Analysis> Analyses { get; set; }
    }
}
