//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareGroup.Mirrors.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        public Analysis()
        {
            this.Widgets = new HashSet<Widget>();
        }
    
        public int AnalysisID { get; set; }
        public int AnalysisGroupID { get; set; }
        public string AnalysisName { get; set; }
        public string AnalysisDescription { get; set; }
        public string AnalysisLayoutData { get; set; }
    
        public virtual AnalysisGroup AnalysisGroup { get; set; }
        public virtual ICollection<Widget> Widgets { get; set; }
    }
}
