//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareGroup.Mirrors.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataConnectionType
    {
        public DataConnectionType()
        {
            this.DataConnections = new HashSet<DataConnection>();
        }
    
        public int ConnectionTypeID { get; set; }
        public string ConnectionTypeName { get; set; }
        public string ProviderName { get; set; }
    
        public virtual ICollection<DataConnection> DataConnections { get; set; }
    }
}
