//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareGroup.Mirrors.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSourceElement
    {
        public int ElementID { get; set; }
        public string ElementName { get; set; }
        public string ElementDataType { get; set; }
        public int SourceID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int SortOrder { get; set; }
        public string ElementType { get; set; }
    
        public virtual DataSource DataSource { get; set; }
    }
}
