//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareGroup.Mirrors.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public int WidgetID { get; set; }
        public int AnalysisID { get; set; }
        public string WidgetData { get; set; }
        public string WidgetUID { get; set; }
        public int WidgetTypeID { get; set; }
        public string WidgetLayoutData { get; set; }
    
        public virtual Analysis Analysis { get; set; }
    }
}
